apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orikerbis/managed-argocd-lab-template
    path: portal
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: portal-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
